// 喫茶去 · 随机推荐池 —— 由 Apple Music 资料库挖掘而来（60 首，跨流派）
export const works = [
  { composer: "Beethoven", title: "Symphony No. 9 in D Minor, Op. 125 \"Choral\"", op: "Beethoven: Symphony No. 9 \"Choral\"", perf: "Sir Georg Solti、Pilar Lorengar 等 · 1972", genre: "古典", minutes: 1267 },
  { composer: "Hizuru", title: "飛鶴", op: "", perf: "Hizuru · 2017", genre: "爵士", minutes: 156 },
  { composer: "Schubert", title: "String Quartet No. 14 in D Minor, D. 810 \"Death and the Maiden\"", op: "Schubert: \"Death and the Maiden\" & \"The Trout\"", perf: "埃米尔・吉列尔斯、阿玛迪斯弦乐四重奏团 · 1998", genre: "古典", minutes: 114 },
  { composer: "Jitterin' Jinn", title: "Tentastic!", op: "", perf: "Jitterin' Jinn · 1999", genre: "流行", minutes: 117 },
  { composer: "Bach", title: "Cantata BWV 147 \"Herz und Mund und Tat und Leben\"", op: "60 Years of the Munich Bach Choir", perf: "Hansjörg Albrecht · 2014", genre: "古典", minutes: 137 },
  { composer: "Susumu Hirasawa", title: "Kyuusai No Gihou", op: "", perf: "Susumu Hirasawa · 1998", genre: "摇滚", minutes: 143 },
  { composer: "Bach", title: "Goldberg Variations, BWV 988", op: "The Goldberg Variations (1981 Recording, Remastered)", perf: "格伦・古尔德 · 1982", genre: "古典", minutes: 534 },
  { composer: "Lin-Manuel Miranda", title: "Hamilton: An American Musical", op: "Original Broadway Cast Recording", perf: "Lin-Manuel Miranda、Leslie Odom Jr. 等 · 2015", genre: "原声/配乐", minutes: 202 },
  { composer: "Rachmaninov", title: "Piano Concerto No. 2 in C Minor, Op. 18", op: "Rachmaninov: Piano Concerto No. 2", perf: "斯维亚托斯拉夫・里赫特 · 1995", genre: "古典", minutes: 417 },
  { composer: "窦唯 & 朝简", title: "琵琶行", op: "琵琶行 - EP", perf: "窦唯、朝简 · 2023", genre: "电子", minutes: 23 },
  { composer: "Schubert", title: "Piano Sonata No. 21 in B-Flat Major, D. 960", op: "Schubert: Piano Sonata D. 960, Moments musicaux D. 780", perf: "威尔海姆・肯普夫 · 1970", genre: "古典", minutes: 318 },
  { composer: "Hochzeitskapelle & Kama Aina", title: "Wayfaring Suite", op: "", perf: "Hochzeitskapelle、Kama Aina · 2018", genre: "民谣", minutes: 94 },
  { composer: "Shostakovich", title: "Symphony No. 7 in C Major, Op. 60 \"Leningrad\"", op: "Bernstein: Puccini - Shostakovich", perf: "莱奥纳德・伯恩斯坦 · 1989", genre: "古典", minutes: 700 },
  { composer: "Nujabes", title: "Spiritual State (feat. Uyama Hiroto)", op: "Spiritual State", perf: "Nujabes · 2011", genre: "嘻哈/R&B", minutes: 26 },
  { composer: "Brahms", title: "Clarinet Quintet in B Minor, Op. 115", op: "Brahms: Quintets · Sextets", perf: "克里斯托夫・艾森巴赫、阿玛迪斯弦乐四重奏团 · 1967", genre: "古典", minutes: 102 },
  { composer: "Camarón de la Isla", title: "La Leyenda del Tiempo (feat. Paco de Lucía)", op: "", perf: "Camarón de la Isla · 1979", genre: "世界音乐", minutes: 37 },
  { composer: "Bach", title: "Cantata BWV 140 \"Wachet auf, ruft uns die Stimme\"", op: "Bach: Cantatas BWV 140, 147", perf: "尼古拉斯・哈农库特 · 1983", genre: "古典", minutes: 44 },
  { composer: "Floyd Cramer", title: "Last Date", op: "", perf: "Floyd Cramer · 1961", genre: "乡村", minutes: 30 },
  { composer: "Bach", title: "Suite in A Major, BWV 832", op: "J.S. Bach: Works for Harpsichord", perf: "阿波・哈基宁 · 2015", genre: "古典", minutes: 14 },
  { composer: "Charlie Porter", title: "Hindsight", op: "", perf: "Charlie Porter · 2021", genre: "爵士", minutes: 129 },
  { composer: "Mahler", title: "Symphony No. 8 in E-Flat Major \"Symphony of a Thousand\"", op: "Mahler: Symphony No. 8", perf: "乔治・索尔蒂、芝加哥交响乐团 等 · 1972", genre: "古典", minutes: 516 },
  { composer: "杏里", title: "Heaven Beach", op: "", perf: "杏里 · 1982", genre: "流行", minutes: 108 },
  { composer: "Haydn", title: "String Quartet in C Major, Op. 76 No. 3 \"Emperor\"", op: "Alban Berg Quartet - The Teldec Recordings", perf: "阿尔班・贝尔格弦乐四重奏 · 1974", genre: "古典", minutes: 90 },
  { composer: "ひとひら", title: "Tsukuru", op: "", perf: "ひとひら · 2023", genre: "摇滚", minutes: 97 },
  { composer: "Bach", title: "Cantata BWV 212 \"Mer hahn en neue Oberkeet\" (Peasant Cantata)", op: "J.S. Bach: Secular Cantatas, Vol. 7", perf: "日本巴赫古乐团、铃木雅明 · 2016", genre: "古典", minutes: 31 },
  { composer: "Howard Shore", title: "The Lord of the Rings: The Two Towers (Soundtrack)", op: "", perf: "霍华德・肖 · 2002", genre: "原声/配乐", minutes: 77 },
  { composer: "Bach", title: "Concerto in D Minor, BWV 974 (after A. Marcello)", op: "Johann Sebastian Bach", perf: "维京格・奥拉夫森 · 2018", genre: "古典", minutes: 68 },
  { composer: "Ian Post", title: "The Highlands", op: "", perf: "Ian Post · 2020", genre: "电子", minutes: 22 },
  { composer: "Berlioz", title: "Symphonie fantastique, Op. 14", op: "Berlioz: Symphonie Fantastique", perf: "克里夫兰管弦乐团、皮埃尔・布列兹 · 1997", genre: "古典", minutes: 454 },
  { composer: "林生祥, 大竹研 & 平安隆", title: "种树", op: "", perf: "林生祥、大竹研 等 · 2006", genre: "民谣", minutes: 59 },
  { composer: "Mozart", title: "Clarinet Quintet in A Major, K. 581", op: "Mozart: Chamber Music", perf: "阿尔班・贝尔格弦乐四重奏 等 · 1990", genre: "古典", minutes: 80 },
  { composer: "Earth, Wind & Fire", title: "Let's Groove", op: "September", perf: "Earth, Wind & Fire · 1978", genre: "嘻哈/R&B", minutes: 18 },
  { composer: "Bach", title: "Cantata BWV 62 \"Nun komm, der Heiden Heiland\"", op: "Bach: Sacred Cantatas, BWV 61-78", perf: "维也纳古乐合奏团、古斯塔夫・莱昂哈特 等 · 2005", genre: "古典", minutes: 25 },
  { composer: "Herbie Hancock & Foday Musa Suso", title: "Moon/Light", op: "Village Life", perf: "Herbie Hancock、Foday Musa Suso · 1985", genre: "世界音乐", minutes: 24 },
  { composer: "Bach", title: "French Suite No. 6 in E Major, BWV 817", op: "Bach: 6 French Suites BWV 812-817", perf: "安德拉斯・席夫 · 1993", genre: "古典", minutes: 63 },
  { composer: "CASIOPEA 3rd", title: "MINT JAMS (Live)", op: "", perf: "CASIOPEA 3rd · 1982", genre: "爵士", minutes: 114 },
  { composer: "Bruckner", title: "Symphony No. 8 in C Minor, WAB 108", op: "Bruckner: Symphony No. 8", perf: "慕尼黑爱乐乐团、塞尔吉乌・切利比达克 · 1998", genre: "古典", minutes: 390 },
  { composer: "Soutaiseiriron", title: "TOWN AGE", op: "", perf: "Soutaiseiriron · 2013", genre: "流行", minutes: 93 },
  { composer: "Dvořák", title: "String Quartet No. 12 in F Major, Op. 96 \"American\"", op: "Dvořák: String Quartet No. 12 & Smetana: No. 1", perf: "爱默生四重奏组 · 1986", genre: "古典", minutes: 31 },
  { composer: "ゆらゆら帝国", title: "空洞です", op: "", perf: "ゆらゆら帝国 · 2007", genre: "摇滚", minutes: 56 },
  { composer: "Bach", title: "Cantata BWV 68 \"Also hat Gott die Welt geliebt\"", op: "Bach: Sacred Cantatas, BWV 67-69a", perf: "根特声乐学院合唱团、菲利普・赫尔维格 等 · 2000", genre: "古典", minutes: 24 },
  { composer: "Rodgers & Hammerstein", title: "The Sound of Music (50th Anniversary Edition)", op: "", perf: "茱丽・安德鲁丝 等 · 1965", genre: "原声/配乐", minutes: 64 },
  { composer: "Bach", title: "Toccata in C Minor, BWV 911", op: "Bach: The 7 Toccatas", perf: "弗朗切斯科・特里斯塔诺 · 2025", genre: "古典", minutes: 38 },
  { composer: "Robin Schulz, David Guetta & Cheat Codes", title: "Shed a Light", op: "Shed a Light - Single", perf: "Robin Schulz、David Guetta 等 · 2016", genre: "电子", minutes: 6 },
  { composer: "Richard Strauss", title: "Eine Alpensinfonie, Op. 64", op: "Richard Strauss: An Alpine Symphony", perf: "柏林爱乐乐团、赫伯特・冯・卡拉扬 · 1993", genre: "古典", minutes: 375 },
  { composer: "Radical Face", title: "Welcome Home, Son", op: "Ghost", perf: "Radical Face · 2007", genre: "民谣", minutes: 54 },
  { composer: "Mendelssohn", title: "String Quintet No. 1 in A Major, Op. 18", op: "Mendelssohn: The String Quintets", perf: "多里克弦乐四重奏、蒂莫西・里杜特 · 2022", genre: "古典", minutes: 31 },
  { composer: "Ryo Fukui & 福居良", title: "Ryo Fukui in New York", op: "", perf: "Ryo Fukui · 1999", genre: "爵士", minutes: 73 },
  { composer: "Bach", title: "Cantata BWV 8 \"Liebster Gott, wenn werd ich sterben\"", op: "Bach: Cantatas BWV 8, 125 & 138", perf: "根特声乐学院合唱团、菲利普・赫尔维格 · 1998", genre: "古典", minutes: 19 },
  { composer: "Engelbert Humperdinck", title: "A Man Without Love", op: "", perf: "英格伯・汉伯汀克 · 1968", genre: "流行", minutes: 84 },
  { composer: "Bach", title: "Chromatic Fantasia & Fugue in D Minor, BWV 903", op: "Bach: Italian Concerto, Chromatic Fantasy & Fugue", perf: "汤・库普曼 · 1992", genre: "古典", minutes: 34 },
  { composer: "Radiohead", title: "OK Computer", op: "", perf: "Radiohead · 1997", genre: "摇滚", minutes: 54 },
  { composer: "Tchaikovsky", title: "Symphony No. 5 in E Minor, Op. 64", op: "Tchaikovsky: Symphony No. 5", perf: "瓦列里・捷杰耶夫、马林斯基交响乐团 · 1992", genre: "古典", minutes: 283 },
  { composer: "Justin Hurwitz", title: "Another Day of Sun", op: "La La Land (Soundtrack)", perf: "艾玛・斯通、Ryan Gosling 等 · 2016", genre: "原声/配乐", minutes: 61 },
  { composer: "Schumann", title: "Piano Quartet in E-Flat Major, Op. 47", op: "Schumann: Piano Quartet Op. 47 (Gould Remastered)", perf: "格伦・古尔德 · 1969", genre: "古典", minutes: 28 },
  { composer: "菊池ひみこ", title: "FLYING BEAGLE", op: "", perf: "菊池ひみこ · 1987", genre: "爵士", minutes: 71 },
  { composer: "Bach", title: "Toccata in E Minor, BWV 914", op: "Bach & Kapustin: Moon Rainbow", perf: "Luisa Imorde · 2025", genre: "古典", minutes: 21 },
  { composer: "Stardust Revue", title: "VOICE", op: "", perf: "Stardust Revue · 1986", genre: "流行", minutes: 48 },
  { composer: "Shostakovich", title: "Piano Quintet in G Minor, Op. 57", op: "Shostakovich: Chamber Music", perf: "布罗茨基四重奏、克里斯蒂安・布莱克肖 · 2007", genre: "古典", minutes: 19 },
  { composer: "Suichu Spica", title: "mEq", op: "", perf: "Suichu Spica · 2021", genre: "摇滚", minutes: 50 }
];
